# 生产镜像，仅包含应用代码
FROM ghcr.io/xinnan-tech/xiaozhi-esp32-server@sha256:6b62dba28638d845920d437f9f958c99bd8dd29c6714381257177b993d7ce43c

COPY main/xiaozhi-server .
COPY deploy/health.py /opt/puppy-deploy/health.py

# 启动应用
CMD ["python", "app.py"]
